### PR TITLE
NotDisjoint now sends component name over grpc

### PR DESCRIPTION
**Pull request by mksm20**
Added component names to components failing due to not_disjoint_action in query response- so when formulating a query response the component name is now transferred over gRPC

### CODE REVIEW

**Review by S3JER — APPROVED** [review]
LGTM

**Review by lugialukas — APPROVED** [review]
LGTM

**Review by t-lohse — COMMENTED** [review]
There is *a lot* duplicate code. Can you mainstream it a bit more, possibly with a function to generate the `LocationTuple` or `State`

**Review by t-lohse — APPROVED** [review]

**Review by lugialukas — APPROVED** [review]
Looks even better to me

**Pull request merged**
